GET http://localhost:3001/api/blogs/

###

GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "",
    "author": "",
    "url": "www.goggle.s"

}

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "pruebaDEELETE1",
    "name": "javi",
    "password": "aaaa"
}

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "pruebaDEELETE2",
    "name": "javi",
    "password": "aaaa"
}

###
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "pruebaDEELETE1",
    "password": "aaaa"
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBydWViYURFRUxFVEUxIiwiaWQiOiI2MDE1OWY1OTVmMTg0ODJlY2RmNzM4NDkiLCJpYXQiOjE2MTIxOTAwNjN9.gJN8ZiIGbu54Yq9gAqlIPewnj35mTzNc3mm-AtjX0bk

{
      "title": "",
    "author": "",
    "url": "www.goggle.s"
}

###
DELETE http://localhost:3003/api/blogs/6015a184cc0e5c30dbf53e10
ontent-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBydWViYURFRUxFVEUyIiwiaWQiOiI2MDE1OWY1YzVmMTg0ODJlY2RmNzM4NGEiLCJpYXQiOjE2MTIwMjk4Njh9.oWk48j1wwQ5LC2M0wcvn-20Yqg3xL7GsRUbe2b2W2yM



